[build]
  command = "yarn build"
  publish = "./src/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200
