[build]
  command = "yarn build"
  YARN_VERSION = "1.17.3"
  functions = "netlify/functions"
  publish = "dist"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://accredify.netlify.app/:splat"
  status = 200
  force = true