[build]
  command = "yarn build"
  YARN_VERSION = "1.17.3"
  publish = "dist"
  NODE_ENV = "production"

[start]
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:1111/api/:splat"
  status = 200
  force = true
  headers = {Content-Type = "application/json"}